### ISSUE TITLE
Support for `ppc`?

### ISSUE THREAD

**Issue by barracuda156** [janestreet/fieldslib#3]
Description seems to imply that [some] 32-bit platforms are not supported. What about PowerPC?
Also, are those unsupported because untested or because something has to be fixed?

**Comment by dkalinichenko-js** [comment]
Hi! 32-bit platforms are not supported due to the lack of testing, see https://discuss.ocaml.org/t/jane-street-packages-dropping-support-for-32-bit/8621.

However, most packages do likely still work on 32-bit. `fieldslib` in particular is very likely to work on 32-bit platforms since it just re-exports Base, and Base has been tested on 32-bit.

**Comment by barracuda156** [comment]
@dkalinichenko-js Thank you for responding. While we are still on OCaml 4.14.x in Macports (and I have not yet tested 5.x), according to OCaml upstream bytecode compiler is supported for all 32-bit archs. (Native was broken for `ppc` anyway, and fixing it turned out non-trivial when I tried, and now no point to bother.)

However it is perfectly possible to test 32-bit Linux on Github CI, if you care.
